version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    ports:
      - "27017:27017"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    # command: python src/main.py
    volumes:
      - .:/app  
    ports: 
      - "3000:3000"
    depends_on:
      - mongodb



    