version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    ports:
      - "27017:27017"
    restart: unless-stopped



    